#!/usr/bin/env ruby
# frozen_string_literal: true

# Owns the iOS flavour wiring in apps/diapason/ios. Run it, never hand-edit what it writes:
#
#   just ios-project          (re)write the Xcode project, schemes, xcconfigs and Podfile
#   just ios-project-check    fail if running it would change anything (CI)
#
# There is no macOS host on this project, so Xcode cannot be used to make these edits, and
# hand-written pbxproj UUIDs are unreviewable. This script uses the `xcodeproj` gem (CocoaPods'
# own, pure Ruby: `gem install --user-install xcodeproj`), is idempotent, and is the single
# source of truth for:
#
#   - {Debug,Release,Profile}-{dev,stg,prod} build configurations, bundle IDs per docs/adr/0013
#   - a base xcconfig per configuration that includes the matching CocoaPods xcconfig
#   - a shared scheme per flavour, derived from Flutter's own Runner.xcscheme
#   - PrivacyInfo.xcprivacy in the Runner target's resources (otherwise it never ships)
#   - IPHONEOS_DEPLOYMENT_TARGET and the Podfile platform, both from tools/versions.env
#
# The iOS launcher label is per-locale (InfoPlist.strings), not per-flavour; see docs/adr/0013.

# The pinned version, not whatever is newest: output is diffed byte for byte (tools/versions.env).
XCODEPROJ_PIN = File.readlines(File.expand_path('../versions.env', __dir__))
                    .find { |l| l.start_with?('XCODEPROJ_VERSION=') }&.split('=', 2)&.last&.strip or
                abort 'tools/versions.env has no XCODEPROJ_VERSION'
gem 'xcodeproj', XCODEPROJ_PIN
require 'xcodeproj'

ROOT = File.expand_path('../..', __dir__)
# The one app under apps/. Not hard-coded, so `just rename` (which may move apps/<slug>) and this
# script cannot disagree about where the iOS project lives.
IOS = begin
  apps = Dir[File.join(ROOT, 'apps/*/ios')]
  abort "expected exactly one apps/*/ios, found #{apps.length}" unless apps.length == 1
  apps.first
end
PROJECT_PATH = File.join(IOS, 'Runner.xcodeproj')
SCHEMES_DIR = File.join(PROJECT_PATH, 'xcshareddata/xcschemes')

FLAVOURS = { 'dev' => '.dev', 'stg' => '.stg', 'prod' => '' }.freeze
# Each flavoured configuration is a copy of Flutter's base configuration of the same build mode.
MODES = { 'Debug' => :debug, 'Release' => :release, 'Profile' => :release }.freeze

def pin(name)
  line = File.readlines(File.join(ROOT, 'tools/versions.env')).find { |l| l.start_with?("#{name}=") }
  abort "tools/versions.env has no #{name}" unless line
  line.split('=', 2).last.strip
end

IOS_TARGET = pin('IOS_DEPLOYMENT_TARGET')

def write_if_changed(path, content)
  return if File.exist?(path) && File.read(path) == content

  File.write(path, content)
  puts "  wrote #{path.delete_prefix("#{ROOT}/")}"
end

def xcconfig(mode, flavour)
  pods = "Pods-Runner.#{"#{mode}-#{flavour}".downcase}.xcconfig"
  <<~XCCONFIG
    // Generated by tools/ios/configure_project.rb - do not edit.
    #include? "Pods/Target Support Files/Pods-Runner/#{pods}"
    #include "Generated.xcconfig"
  XCCONFIG
end

# Copy a configuration's settings into the named configuration, creating it if needed.
def ensure_config(project, list, base, name)
  config = list.build_configurations.find { |c| c.name == name }
  unless config
    config = project.new(Xcodeproj::Project::Object::XCBuildConfiguration)
    config.name = name
    list.build_configurations << config
  end
  config.build_settings = Marshal.load(Marshal.dump(base.build_settings))
  config
end

project = Xcodeproj::Project.open(PROJECT_PATH)
runner = project.targets.find { |t| t.name == 'Runner' } or abort 'no Runner target'

# The base bundle ID lives in exactly one place this script reads: the Runner target's unflavoured
# Release configuration, which Flutter created and `just rename` rewrites. Never a second copy here.
BUNDLE_ID = runner.build_configuration_list['Release']&.build_settings&.fetch('PRODUCT_BUNDLE_IDENTIFIER', nil) or
            abort 'Runner Release has no PRODUCT_BUNDLE_IDENTIFIER'
flutter_group = project.main_group.children.find { |g| g.display_name == 'Flutter' } or abort 'no Flutter group'

# ── Build configurations ─────────────────────────────────────────────────────
MODES.each_key do |mode|
  FLAVOURS.each do |flavour, suffix|
    name = "#{mode}-#{flavour}"

    base = project.build_configuration_list[mode] or abort "no project #{mode} configuration"
    ensure_config(project, project.build_configuration_list, base, name)

    project.targets.each do |target|
      target_base = target.build_configuration_list[mode] or abort "#{target.name} has no #{mode}"
      config = ensure_config(project, target.build_configuration_list, target_base, name)
      config.base_configuration_reference = target_base.base_configuration_reference
      next unless target == runner

      file = "#{name}.xcconfig"
      write_if_changed(File.join(IOS, 'Flutter', file), xcconfig(mode, flavour))
      # Same shape as Flutter's own Debug.xcconfig reference: the Flutter group has no path.
      ref = flutter_group.files.find { |f| f.path == "Flutter/#{file}" } ||
            flutter_group.new_reference("Flutter/#{file}")
      ref.name = file
      ref.last_known_file_type = 'text.xcconfig'
      config.base_configuration_reference = ref
      config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = "#{BUNDLE_ID}#{suffix}"
    end
  end
end

# One deployment target everywhere, from the pin.
([project] + project.targets).each do |owner|
  owner.build_configuration_list.build_configurations.each do |config|
    next unless owner == project || config.build_settings.key?('IPHONEOS_DEPLOYMENT_TARGET')

    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_TARGET
  end
end

# ── Privacy manifest ─────────────────────────────────────────────────────────
runner_group = project.main_group.children.find { |g| g.path == 'Runner' } or abort 'no Runner group'
privacy = runner_group.files.find { |f| f.path == 'PrivacyInfo.xcprivacy' } ||
          runner_group.new_reference('PrivacyInfo.xcprivacy')
privacy.last_known_file_type = 'text.xml'
runner.resources_build_phase.add_file_reference(privacy, true)

project.save

# ── Schemes ──────────────────────────────────────────────────────────────────
# Derived from Runner.xcscheme by renaming its configurations, so Flutter's own scheme settings
# (the LLDB init file, GPU validation) carry over unchanged.
template = File.read(File.join(SCHEMES_DIR, 'Runner.xcscheme'))
FLAVOURS.each_key do |flavour|
  scheme = template.gsub(/buildConfiguration = "(Debug|Release|Profile)"/) do
    %(buildConfiguration = "#{Regexp.last_match(1)}-#{flavour}")
  end
  write_if_changed(File.join(SCHEMES_DIR, "#{flavour}.xcscheme"), scheme)
end

# ── Base xcconfigs and Podfile ───────────────────────────────────────────────
# Flutter adds these CocoaPods includes on first build if they are missing, which would make a
# clean CI build mutate tracked files. Commit them instead.
{ 'Debug' => 'debug', 'Release' => 'release' }.each do |mode, pods|
  write_if_changed(File.join(IOS, 'Flutter', "#{mode}.xcconfig"), <<~XCCONFIG)
    #include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.#{pods}.xcconfig"
    #include "Generated.xcconfig"
  XCCONFIG
end

# Without this mapping CocoaPods treats every configuration it does not recognise as release, so
# Debug-dev would silently link release pods.
mapping = MODES.flat_map do |mode, kind|
  [mode, *FLAVOURS.keys.map { |f| "#{mode}-#{f}" }].map { |n| "  '#{n}' => :#{kind}," }
end.join("\n")

write_if_changed(File.join(IOS, 'Podfile'), <<~PODFILE)
  # Generated by tools/ios/configure_project.rb from Flutter's Podfile-ios template - do not edit.
  platform :ios, '#{IOS_TARGET}'

  # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
  ENV['COCOAPODS_DISABLE_STATS'] = 'true'

  project 'Runner', {
  #{mapping}
  }

  def flutter_root
    generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
    unless File.exist?(generated_xcode_build_settings_path)
      raise "\#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end

    File.foreach(generated_xcode_build_settings_path) do |line|
      matches = line.match(/FLUTTER_ROOT\\=(.*)/)
      return matches[1].strip if matches
    end
    raise "FLUTTER_ROOT not found in \#{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
  end

  require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

  flutter_ios_podfile_setup

  target 'Runner' do
    use_frameworks!

    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
    target 'RunnerTests' do
      inherit! :search_paths
    end
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      # permission_handler compiles in only the permissions an app enables. This app asks for the
      # microphone and nothing else, so no other usage API reaches the binary (T-002b).
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'PERMISSION_MICROPHONE=1'
      end
    end
  end
PODFILE

puts 'iOS project configured.'
