// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member

import 'package:audio_engine/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioSession>>
abstract class AudioSession implements RustOpaqueInterface {
  /// Deliver a snapshot to `sink` about 30 times a second, replacing any earlier subscriber.
  /// Delivery stops when Dart cancels the stream.
  ///
  /// # Errors
  /// [`AudioSessionError::Gone`] if the session has shut down.
  Stream<SessionSnapshotDto> snapshots();

  /// Start the session thread on this platform's backend. No stream opens until [`start`].
  ///
  /// [`start`]: AudioSession::start
  ///
  /// # Errors
  /// [`AudioSessionError::Spawn`] if the thread cannot be created.
  static AudioSession spawn() => RustLib.instance.api.crateApiSessionAudioSessionSpawn();

  /// Run the stream, with the microphone if `input`. Returns at once.
  ///
  /// # Errors
  /// [`AudioSessionError::Gone`] if the session has shut down.
  void start({required bool input});

  /// Play a test tone, kept across stream rebuilds until stopped.
  ///
  /// # Errors
  /// [`AudioSessionError::Gone`] if the session has shut down.
  void startTone({required double frequencyHz, required double amplitude});

  /// Close the stream. Returns at once.
  ///
  /// # Errors
  /// [`AudioSessionError::Gone`] if the session has shut down.
  void stop();

  /// Stop the test tone.
  ///
  /// # Errors
  /// [`AudioSessionError::Gone`] if the session has shut down.
  void stopTone();
}

/// Why the session could not take a request.
enum AudioSessionError {
  /// The session thread could not be started.
  spawn,

  /// The session has shut down.
  gone,
}

/// Why something failed. Mirrors `diapason_session::Fault`.
enum FaultDto {
  /// The microphone permission is missing.
  permissionDenied,

  /// The device is gone, busy or broken.
  deviceUnavailable,

  /// The device refused the configuration.
  configurationUnsupported,

  /// A bug in this app.
  internal,
}

/// The microphone processing the device applied. Mirrors `diapason_audio_io::InputPreset`.
enum InputPresetDto {
  /// No processing.
  unprocessed,

  /// Automatic gain off on most devices.
  voiceRecognition,

  /// Anything else; `input_preset_code` has the platform's value.
  other,
}

/// One session snapshot, flattened for Dart. Field meanings are documented on
/// `diapason_session::SessionSnapshot`, which this mirrors.
class SessionSnapshotDto {
  const new({
    required this.state,
    required this.backend,
    required this.sampleRate,
    required this.inputActive,
    required this.inputRms,
    required this.frames,
    required this.callbacks,
    required this.worstCallbackNs,
    required this.inputUnderruns,
    required this.rebuilds,
    required this.commandsDropped,
    this.maxBlockFrames,
    this.toneHz,
    this.xruns,
    this.framesPerBurst,
    this.inputPreset,
    this.inputPresetCode,
    this.outputLowLatency,
    this.outputExclusive,
    this.inputLowLatency,
    this.inputExclusive,
    this.fault,
    this.inputFault,
    this.lastError,
  });

  /// Lifecycle state.
  final SessionStateDto state;

  /// Backend name.
  final String backend;

  /// The rate the stream runs at. Zero while no stream is open.
  final int sampleRate;

  /// Largest block the callback may be given. `None` with no stream open.
  final int? maxBlockFrames;

  /// Whether the open stream has the microphone.
  final bool inputActive;

  /// Input RMS over the last 50 ms window.
  final double inputRms;

  /// The test tone's frequency while it plays.
  final double? toneHz;

  /// Frames the current stream has played.
  final int frames;

  /// Callbacks the current stream has completed.
  final int callbacks;

  /// Slowest callback of the current stream, in nanoseconds.
  final int worstCallbackNs;

  /// Blocks the microphone delivered late.
  final int inputUnderruns;

  /// Platform-counted underruns and overruns.
  final int? xruns;

  /// The output's burst size, in frames.
  final int? framesPerBurst;

  /// The input preset obtained.
  final InputPresetDto? inputPreset;

  /// The platform's raw value for the input preset obtained.
  final int? inputPresetCode;

  /// Whether the output got the low-latency path.
  final bool? outputLowLatency;

  /// Whether the output got exclusive mode.
  final bool? outputExclusive;

  /// Whether the input got the low-latency path.
  final bool? inputLowLatency;

  /// Whether the input got exclusive mode.
  final bool? inputExclusive;

  /// Streams rebuilt after the platform broke one.
  final int rebuilds;

  /// Why the session failed.
  final FaultDto? fault;

  /// Why the stream runs without the microphone it was asked for.
  final FaultDto? inputFault;

  /// The most recent backend error, as text, for support reports.
  final String? lastError;

  /// Commands the audio thread's queue could not take.
  final int commandsDropped;

  @override
  int get hashCode =>
      state.hashCode ^
      backend.hashCode ^
      sampleRate.hashCode ^
      maxBlockFrames.hashCode ^
      inputActive.hashCode ^
      inputRms.hashCode ^
      toneHz.hashCode ^
      frames.hashCode ^
      callbacks.hashCode ^
      worstCallbackNs.hashCode ^
      inputUnderruns.hashCode ^
      xruns.hashCode ^
      framesPerBurst.hashCode ^
      inputPreset.hashCode ^
      inputPresetCode.hashCode ^
      outputLowLatency.hashCode ^
      outputExclusive.hashCode ^
      inputLowLatency.hashCode ^
      inputExclusive.hashCode ^
      rebuilds.hashCode ^
      fault.hashCode ^
      inputFault.hashCode ^
      lastError.hashCode ^
      commandsDropped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSnapshotDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          backend == other.backend &&
          sampleRate == other.sampleRate &&
          maxBlockFrames == other.maxBlockFrames &&
          inputActive == other.inputActive &&
          inputRms == other.inputRms &&
          toneHz == other.toneHz &&
          frames == other.frames &&
          callbacks == other.callbacks &&
          worstCallbackNs == other.worstCallbackNs &&
          inputUnderruns == other.inputUnderruns &&
          xruns == other.xruns &&
          framesPerBurst == other.framesPerBurst &&
          inputPreset == other.inputPreset &&
          inputPresetCode == other.inputPresetCode &&
          outputLowLatency == other.outputLowLatency &&
          outputExclusive == other.outputExclusive &&
          inputLowLatency == other.inputLowLatency &&
          inputExclusive == other.inputExclusive &&
          rebuilds == other.rebuilds &&
          fault == other.fault &&
          inputFault == other.inputFault &&
          lastError == other.lastError &&
          commandsDropped == other.commandsDropped;
}

/// Where the session is in its lifecycle. Mirrors `diapason_session::SessionState`.
enum SessionStateDto {
  /// No stream, and none wanted.
  stopped,

  /// A stream is open and running.
  running,

  /// Waiting to reopen a broken stream.
  recovering,

  /// Gave up; see the fault.
  failed,
}
