// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import

import 'package:audio_engine/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Read which builds are linked. Synchronous: it reads constants. Stream state is not here; it
/// arrives as snapshots from [`crate::api::session::AudioSession::snapshots`].
EngineStatus engineStatus() => RustLib.instance.api.crateApiSimpleEngineStatus();

/// Which builds of the Rust stack are running, as seen from Dart.
///
/// Built from [`diapason_session::BuildInfo`] rather than re-exporting it, because the mapping
/// across the boundary is this crate's whole job and the engine type must stay free to change
/// shape without the FFI layer silently following it.
class EngineStatus {
  const new({required this.dspBuild, required this.engineBuild});

  /// Identifies the DSP crate at the bottom of the Rust stack.
  final String dspBuild;

  /// Identifies the engine crate.
  final String engineBuild;

  @override
  int get hashCode => dspBuild.hashCode ^ engineBuild.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineStatus &&
          runtimeType == other.runtimeType &&
          dspBuild == other.dspBuild &&
          engineBuild == other.engineBuild;
}
